// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("./stdlib/belt_Array.js");

Belt_Array.forEach(/* array */[
      1,
      2,
      3,
      4,
      5
    ], (function (prim) {
        console.log(prim);
        return /* () */0;
      }));

/*  Not a pure module */

