import "@babel/polyfill";
import { Polestar, DefaultResolver } from "polestar";

let defaultResolver = new DefaultResolver();
const bs_stdlib = "http://localhost:3000/";

let polestar = new Polestar({
  globals: {
    process: {
      env: {},
    },
  },
  moduleThis: window,
  fetcher: async (url, meta) => {
    console.log("fetcher", url, meta);

    if (url === "vfs:///index.js") {
      return {
        url: url,
        id: url,
        dependencies: ["./stdlib/js_mapperRt.js"],
        code: `// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require(\"./stdlib/js_mapperRt.js\");

var jsMapperConstantArray = /* array */[
  1,
  2,
  4,
  8
];

function tToJs(param) {
  return Js_mapperRt.toInt(param, jsMapperConstantArray);
}

function tFromJs(param) {
  return Js_mapperRt.fromInt(4, jsMapperConstantArray, param);
}

var a = tToJs(/* Hint */0);

console.log(a);

exports.tToJs = tToJs;
exports.tFromJs = tFromJs;
exports.a = a;
/* a Not a pure module */`,
      };
    }

    console.log(url, meta);

    const { originalRequest, requiredById } = meta;

    if (originalRequest && originalRequest.startsWith("./stdlib/")) {
      let response = await fetch(bs_stdlib + originalRequest.slice(2));
      let code = await response.text();
      return {
        url: url,
        id: url,
        dependencies:[],
        code,
      };
    }
    return null;
  },
  resolver: defaultResolver,
  onEntry: (...args) => {
    console.log("onEntry", ...args);
  },
  onError: error => {
    console.error(error);
  },
});

async function main() {
  let indexModule = await polestar.require("react");
  console.log(indexModule);
}

main();
