// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE


function str(prim) {
  return prim;
}

function valueFromEvent(evt) {
  return evt.target.value;
}

export {
  str ,
  valueFromEvent ,
  
}
/* No side effect */
